Astrodevil/Programming-Basics

- Java/cbse_result.java
- Java/grade.java
- Java/greeting.java
- Java/helloworld.java
- Java/loops.java
- Java/rock_paper_scissors.java
- Java/string_methods.java
- Java/sum.java
> Java Programs

- C++/happy number.cpp
The program check whether a number is happy or not
A happy number is the one:
Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Example 1:
19 is happy
Explanation:
1^2 + 9^2 = 82
8^2 + 2^2 = 68
6^2 + 8^2 = 100
1^2 + 0^2 + 0^2=1
> happy number.cpp

- C++/introtoclass.cpp
added a quick intro about classes
> added a quick intro about classes

- Java/Niven.java
- Java/reverse.java
The program below is used to reverse an array 
for example an array of {1,2,3,4,5}
will become {5,4,3,2,1} upon reversing
> Reverse An Array

- C++/Matrix multiplication.cpp
- C++/Program to reverse number.cpp
- C++/Program to swap two numbers without third variable.cpp
Resolves #38 
Added programs:
1. Matrix Multiplication
2. Swap 2 numbers without extra space (variable)
3. Reverse and output a given number
> Added 3 new programs into C++

- C++/Right_Lower_Triangle.cpp
Program to print Lower Right Triangle using cpp.
By sam-79
> C++ File Added

- DSA/DSA-CPP/Linked List Basics/Circular_LL.cpp
- DSA/DSA-CPP/Linked List Basics/CycleFloyd.cpp
- DSA/DSA-CPP/Linked List Basics/DoublyLL.cpp
- DSA/DSA-CPP/Linked List Basics/InsertionSearchDeletion.cpp
- DSA/DSA-CPP/Linked List Basics/ReverseAList.cpp
- DSA/DSA-CPP/Stacks/Postfix.cpp
- DSA/DSA-CPP/Stacks/Prefix.cpp
- DSA/DSA-CPP/Stacks/PrintReverse.cpp
- DSA/DSA-CPP/Stacks/PushPopEmpty.cpp
- DSA/DSA-CPP/Stacks/Reverse.cpp
Added Linked List and Stack Codes.
#69
> Adding Linear Data Structure

- DSA/Sorting Algo/BubbleSort.cpp
- DSA/Sorting Algo/SelectionSort.cpp
I have added Bubble Sort and Selection sort.
#77
> Bubble Sort and Selection Sort

- C++/ExceptionHandlingUsingTryCatch.cpp
- C++/Foreachloop.cpp
Added two C++ Programs
1. Foreachloop.cpp : It demonstrates Foreach loop in C++
2.ExceptionHandlingUsingTryCatch.cpp : It Demonstrates Exception Handling in C++.
> Added 2 More C++ Programs(Foreachloop.cpp, ExceptionHandlingUsingTryCatch.cpp)

- DSA/Basic-DSA-Questions/Sub Array Sum/SumOfSubArray.cpp
I have added the code of printing all the sub array sum of given array size.
#89
> Adding code of subarray sum

- C++/calcAdvance.cpp
a new c++ file is added in c++ section in which new code is added if someone wants to perform operations more than 1 one
> added calcAdvance

- STL/2d_Vector.cpp
- STL/Array.cpp
- STL/Vector.cpp
- STL/calculator_using_templatefnc.cpp
- STL/compare_sortfnc.cpp
- STL/deque.cpp
- STL/list.cpp
- STL/map.cpp
- STL/pair.cpp
- STL/priority_queue.cpp
- STL/queue.cpp
- STL/set.cpp
Kindly Merge The PR sir. I have successfully added programs for different containers of Standard Template Library in C++ (including 2-d Vector , Priority_Queue etc).
> Added Codes for multiple containers of STL

- C/Queue.h
> Queue header for C

- Python/Games/tictactoe.py
Created a games folder in python and added the program for unbeatable tictactoe written in python
fixes : #157
> added tictactoe in python--games

- C++/Trapping Rain Water.cpp
I am a participant of **Hacktoberfest 2021**. Kindly review and merge this branch or please label it as 'hacktoberfest-accepted' . Thank You !!
**Question :** Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
**Solution :** The solution is in C++ language.
**Related Issue** : #158
> Added Trapping Rain Water.cpp

- DSA/Array implementation in C/README.MD
- DSA/Array implementation in C/deletion.c
- DSA/Array implementation in C/insertion.c
- DSA/Array implementation in C/traversal.c
- Python/Projects/Steganography Project/README.MD
- Python/Projects/Steganography Project/decrypt_steganography.py
- Python/Projects/Steganography Project/encrypt_steganography.py
Made a very realistic project in Python for **steganography**. 
> The process of hiding a text message inside a media file is called steganography.   
My code can encode a message with an image that can be decoded only through the decryption code. It's the new source of communication that can't be tracked or decrypted as 3rd person won't have decryption code with him.
Completely written in Python.  Added a README file with complete details.
Tag this under 'Hacktober fest 2021'.
> New project on Python

- C++/recursivefactorial.cpp
I implemented a recursive factorial algorithm using C++. Checking the folder, I saw that there was a factorial algorithm but it was using a for loop. I thought that it would be a good idea to add a factorial algorithm using recursion.
> Implemented a recursive factorial algorithm in Cpp

- C/Dijkstra's Algorithm.c
- C/Heap_Sort.c
- C/infixToPostfix.c
> Added some Algorithms

- C++/string_to_binary_converter.cpp
This program converts any string to its binary form.
> string to binary converter

- C++/C++Template.cpp
Added the stated program in accordance with #107
> Added C++ program to demonstrate the use of template to create generic classes

- DSA/Basic-DSA-Questions/Sum of Nodes of linked list/UsingRecursion.cpp
- DSA/Basic-DSA-Questions/Sum of Nodes of linked list/WithoutRecursion.cpp
I have added a folder containing the code for displaying the sum of the nodes of the linked list by using recursion as well as without recursion in the following location -> DSA\Basic-DSA-Questions
> sum of nodes of linked list (c++)

- Python/replace.py
This python inbuilt replace function is implemented using recurrsion
> Added python Inbuilt function program

- DSA/DSA-Java/BinarySearch.java
Hey there I have Added Binary Search Java Program In DSA-Java folder inside DSA folder.
> Added Binary Search in DSA-java

- C++/link list functions.cpp
- C++/main.cpp
These are few functions associated with single link list which can help while working with projects.
> Link list functions added

- DSA/DSA-Java/Heaps/BinaryHeap.java
- DSA/DSA-Java/LinkedList/Circularll.java
- DSA/DSA-Java/LinkedList/Doublyll.java
- DSA/DSA-Java/LinkedList/Singlyll.java
- DSA/DSA-Java/Queue/Queue.java
- DSA/DSA-Java/Stack/StackArray.java
- DSA/DSA-Java/Stack/Stackll.java
- DSA/DSA-Java/Trees/BinarySearchTree/BST.java
- DSA/DSA-Java/Trees/BinaryTree/BinaryTree.java
- DSA/DSA-Java/Trees/BinaryTree/BinaryTreeArray.java
Added programs of  Data Structure in Java language 
topics are:
1)Linked List
-Singly Linked List
-Doubly Linked List
-Circular Linked List
Stack 
-Using array
-Using a linked list
Queue
Tree
-Binary Tree
-Binary Search Tree
Heap
-Binary Heap
> Added Data Structure in Java language 

- Java/SmallerNumbers.java
I have added a file in java folder i.e. SmallerNumber.java
> Added SmallerNumber.java

- Python/Utility/Passowrd Generator/README.md
- Python/Utility/Passowrd Generator/passwd gen.py
- Python/Utility/README.md
1. Initialized Python/Utility folder with a README.md
2. Added Password Generator with "password gen.py" and README.md
close #223
> Created Utility folder and Added Password Generator in it

- DSA/Basic-DSA-Questions/FirstMissingPositive/FirstMissingPositive.cpp
Successfully Implemented First Missing Positive Integer, for #237 issue
> Added First Missing Positive Integer

- Java/last_word.java
Given a string s consisting of some words 
* separated by some number of spaces, 
* return the length of the last word in the string.
* for example Hello World
* will give 5
* as The last word is "World" with length 5
This is in reference to #48
> last_word.java

- DSA/Sorting Algo/InsertionSort.cpp
Hey, i've added Insertion sort pgm in C++ with proper comments, pls check!
> InsertionSort C++ pgm added!

- Python/Projects/Comment_Section_Automation/EmailAndPhoneNumExtractor.py
- Python/Projects/Comment_Section_Automation/README.md
Added a python script which extracts telephone no.s, mobile no.s and email address from a text file and writes them into a separate text file.
This PR closes #116.
> Python Script to extract phone no. and email address from a text file added

- C++/fibonacci-recursion.cpp
Looking at the C++ folder, there is already a Fibonacci algorithm implemented. However, it is iterative. It would be nice to also have a Fibonacci Algorithm using Recursion, since it is a great algorithm for beginners to understand recursion better.
This would close the Issue #244.
> Fix #244 - Fibonacci Algorithm using Recursion

- C++/words counter.cpp
This is a C++ program that counts the number of words in a sentence entered by the user.
> Word counter

- C++/factorial_recursion.cpp
Kindly merge it if you find it useful and label it as hacktoberfest
Issue #193
> Add neat factorial recursion function

- Python/fibonacci.py
Print fibonacci number with given index.
> fibonacci.py added

- C++/patterns/PascalTrianlge.cpp
Added a Pascal's Triangle pattern using cpp in pattern C+++/Pattern folder, hope you will review it soon, thanks in advance.
:) 
#260 issue.
if the user enter `7` in the input, then following pattern with `7` rows is printed:
> Added Pascal's Trianlge Pattern (C++)

- Python/Utility/Lazy Junk Organizer/README.md
- Python/Utility/Lazy Junk Organizer/lazyjunkorganizer.py
Lazy Junk Organizer and it's README.md file added under [Python/Utility](https://github.com/Astrodevil/Programming-Basics/tree/main/Python/Utility). 
closes #250 @Astrodevil
> Added Lazy Junk Organizer

- Python/Utility/Random Item Chooser/README.md
- Python/Utility/Random Item Chooser/choose.py
Added Random Item Chooser under [Python/Utility](https://github.com/Astrodevil/Programming-Basics/tree/main/Python/Utility).
Closes #251
> Added Random Item Chooser

- Java/Simple Games/Connect Four/ConnectFour.java
- Java/Simple Games/Connect Four/README.md
This is a program for the game Connect Four
Close #405
> ConnectFour game

- Java/Temperature_Conversion.java
- Added temperature conversion program into Java folder.
- Close #404
> Temp conversion

- Java/AddTwoNumbers.java
Code to add two numbers given as a list.
> Added AddTwoNumbers.java

- Python/serial.py
Quick tutorial file for reading data over a serial port, such as a Raspberry Pi or Arduino.
> How to read data from Serial on Python3

- Python/Birthday wish calculator.py
I had added the code for the Birthday wish calculator program 
you can look at the issue[here](https://github.com/Astrodevil/Programming-Basics/issues/351#issuecomment-939241767)
>  Birthday wish calculator.py

- C++/Fizz_Buzz.cpp
hey there. please merge my pull.
> LeetCode problem no 412 solution in Cpp added

- DSA/DSA-CPP/STL/set.cpp
Completed the code it was missing
> Set in Cpp

- README.md
> Corrected Hacktoberfest image
